/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bhavin;

/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
   By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 * @author bhavin
 */
public class Problem2 {
    
    static int sum = 0;
    
    public int Problem2(int n){
        
        if(n <= 1)
            return n;
        else
        {
            return Problem2(n - 1) + n;
        }
        
    }
    
    public static void main(String args[]){
        Problem2 f = new Problem2();
        sum = f.Problem2(10);
        System.out.println(sum);
    }
}
